BlogApp/urls.py
from django.urls import path
from BlogApp import views

app_name = 'BlogApp'

urlpatterns = [
    path('', views.BlogList.as_view(), name='blog_list'),
    path('write/', views.CreateBlog.as_view(), name='create_blog'),
    path('blogdetails/<str:slug>', views.blog_details, name='blog_details'),
    path('liked/<pk>',views.like, name='liked_post'),
    path('unliked/<pk>', views.unlike, name='unliked_post'),
    path('myblogs/', views.MyBlogs.as_view(), name='my_blogs'),
    path('edit_blog/<pk>', views.BlogUpdate.as_view(), name='edit_blog'),
]

BlogProject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('BlogApp.urls')),
    path('account/', include('LogInApp.urls')),
    path('',views.index, name='index'),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BlogApp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Blog(models.Model):
    author = models.ForeignKey(User, on_delete= models.CASCADE, related_name='post_author')
    blog_title = models.CharField(max_length=300,verbose_name='Put a Title')
    slug = models.SlugField(unique=True)
    blog_content = models.TextField(verbose_name='What is on your mind?')
    blog_image = models.ImageField(upload_to='blog_images', verbose_name='Image')
    publish_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ('-publish_date',)
    
    
    def __str__(self):
        return self.blog_title
    
    
class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name="blog_comment")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comment')
    comment = models.TextField()
    comment_date = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ('-comment_date',)
    
    def __str__(self):
        return self.comment

class Like(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='liked_blog')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='liker_user')
    
    def __str__(self):
        return self.user+ 'Likes' + self.blog

BlogApp/forms.py
from django import forms
from BlogApp.models import Blog, Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']
        

BlogApp/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.views.generic import CreateView, UpdateView, ListView, DeleteView, DetailView, View, TemplateView
from django.urls import reverse, reverse_lazy
from BlogApp.models import Blog, Comment, Like
from django.contrib.auth.decorators import login_required

from django.contrib.auth.mixins import LoginRequiredMixin
import uuid
from BlogApp.forms import CommentForm
# Create your views here.

class CreateBlog(LoginRequiredMixin,CreateView):
    model = Blog
    template_name = 'BlogApp/create_blog.html'
    fields = ('blog_title', 'blog_content', 'blog_image')
    
    def form_valid(self, form):
        blog_obj = form.save(commit=False)
        blog_obj.author = self.request.user
        title = blog_obj.blog_title
        blog_obj.slug = title.replace(" ", "-")+ "-" + str(uuid.uuid4())
        blog_obj.save()
        return HttpResponseRedirect(reverse('index'))
    
    
class BlogList(ListView):
    context_object_name = 'blogs'
    model = Blog
    template_name = 'BlogApp/blog_list.html'
    # queryset = Blog.objects.order_by('-publish_date')
    

@login_required
def blog_details(request, slug):
    blog = Blog.objects.get(slug=slug)
    comment_form = CommentForm()
    alreadyliked = Like.objects.filter(blog=blog, user=request.user)
    
    if alreadyliked:
        liked = True
    else:
        liked = False
    
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.blog = blog
            comment.save()
            return HttpResponseRedirect(reverse('BlogApp:blog_details', kwargs={'slug': slug}))
    
    diction = {'blog': blog, 'comment_form': comment_form, 'liked':liked}
    return render(request, 'BlogApp/blog_details.html', context=diction)


@login_required
def like(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    alreadyliked = Like.objects.filter(blog=blog, user=user)
    if not alreadyliked:
        liked_post = Like(blog=blog, user=user)
        liked_post.save()
    
    return HttpResponseRedirect(reverse('BlogApp:blog_details', kwargs={'slug': blog.slug}))


@login_required
def unlike(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    alreadyliked = Like.objects.filter(blog=blog, user=user)
    alreadyliked.delete()
    return HttpResponseRedirect(reverse('BlogApp:blog_details', kwargs={'slug': blog.slug}))
    

class MyBlogs(LoginRequiredMixin, TemplateView):
    template_name = 'BlogApp/my_blogs.html'
    


class BlogUpdate(LoginRequiredMixin, UpdateView):
    model = Blog
    fields = ['blog_title', 'blog_content', 'blog_image']
    template_name = 'BlogApp/edit_blog.html'
    
    def get_success_url(self, **kwargs):
        return reverse_lazy('BlogApp:blog_details', kwargs={'slug': self.object.slug})

templates/BlogApp/blog_details.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{blog.blog_title}} {% endblock %}

{% block body_block %}

<div class="row">
    <div class="col-sm-6">
        <h2>{{blog.blog_title}}</h2>
        <h4>Posted By: @{{blog.author}}</h4>
        <h6>Published on: {{blog.Publish_date}}</h6>
        <h6>Update on: {{blog.update_date}}</h6>
        <h6>{{blog.liked_blog.count}} Likes | {{blog.blog_comment.count}} Comments</h6>
    </div>
    <div class="col-sm-6">
        <img src="/media/{{blog.blog_image}}" alt="" width="100%"> <br>
    </div>
    <p>{{blog.blog_content|linebreaks}}</p>
    <hr>
</div>
{% if not liked %}
<a href="{% url 'BlogApp:liked_post' pk=blog.pk %}">
    <i class="fa fa-thumbs-up" aria-hidden="true"></i>
</a>
{% else %}
<a href="{% url 'BlogApp:unliked_post' pk=blog.pk %}">
    <i class="fa fa-thumbs-down" aria-hidden="true"></i>
</a>
{% endif %}

<div class="row">
    <div class="col-sm-6">
        <hr>
        <h5>Comments:</h5>
        {% for comment in blog.blog_comment.all %}

        <p> <a href="">@{{comment.user}} </a> </p>
        <h3> {{comment.comment}} </h3>
        <h6>{{comment.comment_date}}</h6>

        {% endfor %}
        
    </div>
    <div class="col-sm-6">
        <form action="" method="POST">
            {% csrf_token %}
            {{comment_form|crispy}}
            <button type="submit" class="btn btn-warning btn-sm">comment</button>
        </form>
    </div>
</div>
<br> <br>

{% endblock %}

templates/BlogApp/blog_list.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title_block %} Home {% endblock %}

{% block body_block %}
<h1>Blog Site</h1>

{% for blog in blogs %}

<h3>{{blog.blog_title}}</h3>
<h6>{{blog.publish_date}}</h6>

<div class="row">
    <div class="col-sm-4">
        <img src="/media/{{blog.blog_image}}" alt="{{blog.blog_image}}" title="{{blog.blog_title}}" width="100%">
    </div>
    <div class="col-sm-8">
        <p>{{ blog.blog_content|range_filter|linebreaks }} <a href="{% url 'BlogApp:blog_details' slug=blog.slug %}">Read More....</a> </p>
        <h6>Posted By: <a href="">@{{blog.author}}</a> </h6>
        <h6>{{blog.liked_blog.count}} Likes | {{blog.blog_comment.count}} Comments</h6>
    </div>
</div>
<hr>

{% endfor %}

{% endblock %}

templates/BlogApp/create_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Blog Details {% endblock %}

{% block body_block %}
<p>Write Blogs:</p>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success btn-sm">Publish</button>
</form>

{% endblock %}

templates/BlogApp/edit_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{blog.blog_title}}  {% endblock %}

{% block body_block %}

{% if blog.author == user %}

<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit" class="btn btn-warning btn-sm">Update</button>
</form>

{% else %}
<p>You are not allowed to view this page : 404</p>

{% endif %}

{% endblock %}

templates/BlogApp/my_blogs.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title_block %} {{user}} {% endblock %}

{% block body_block %}

{% for blog in user.post_author.all %}
<h3>{{blog.blog_title}}</h3>
<h6>{{blog.publish_date}}</h6>

<div class="row">
    <div class="col-sm-4">
        <img src="/media/{{blog.blog_image}}" alt="" width="100%">
    </div>
    <div class="col-sm-8">
        <p>{{blog.blog_content|range_filter|linebreaks}}</p>
        <a href="{% url 'BlogApp:blog_details' slug=blog.slug %}">Read More...</a>
    </div>
</div>

<a href="{% url 'BlogApp:edit_blog' pk=blog.pk %}">Edit</a>
<hr>
{% endfor %}

{% endblock %}