BlogApp/urls.py
from django.urls import path
from BlogApp import views

app_name = 'BlogApp'

urlpatterns = [
    path('', views.BlogList.as_view(), name='blog_list'),
    path('write/', views.CreateBlog.as_view(), name='create_blog'),
    path('blogdetails/<str:slug>', views.blog_details, name='blog_details'),
    path('liked/<pk>',views.like, name='liked_post'),
    path('unliked/<pk>', views.unlike, name='unliked_post'),
    path('myblogs/', views.MyBlogs.as_view(), name='my_blogs'),
    path('edit_blog/<pk>', views.BlogUpdate.as_view(), name='edit_blog'),
]

BlogProject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('BlogApp.urls')),
    path('account/', include('LogInApp.urls')),
    path('',views.index, name='index'),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LogInApp/urls.py
from django.urls import path
from LogInApp import views


app_name = 'LogInApp'

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('change-profile/', views.user_change, name='change_profile'),
    path('password/', views.pass_change, name='password'),
    path('addprofilepic/', views.add_profile_pic, name='add_profile_pic'),
    path('change_profile/', views.change_pro_pic, name='change_profile_pic'),
]

LogInApp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name= 'user_profile', on_delete=models.CASCADE)
    profile_pics = models.ImageField(upload_to='profile_pics')

LogInApp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from LogInApp.models import UserProfile


class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True, label='Email Address')
    class Meta:
        model = User
        fields = ('username', 'email' ,'password1','password2')
        
        
class User_Profile_Change(UserChangeForm):
    class Meta:
        model = User
        fields = ('username','email', 'first_name', 'last_name', 'password')
        
class Profile_Pic(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['profile_pics',]

LogInApp/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login, logout, authenticate
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from LogInApp.forms import SignUpForm, User_Profile_Change, Profile_Pic
# Create your views here.


def sign_up(request):
    form = SignUpForm()
    registered = False
    if request.method=='POST':
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            form.save()
            registered = True
            
    diction = {'form':form, 'registered':registered}
    return render(request, 'LogInApp/signup.html', context=diction)


def log_in(request):
    form = AuthenticationForm()
    if request.method=='POST':
        form= AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            
    
    diction={'form':form}
    return render(request, 'LogInApp/login.html', context=diction)


@login_required
def log_out(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def profile(request):
    diction = {}
    return render(request, 'LogInApp/profile.html', context=diction)


@login_required
def user_change(request):
    current_user = request.user
    form = User_Profile_Change(instance=current_user)
    if request.method == 'POST':
        form = User_Profile_Change(request.POST, instance=current_user)
        if form.is_valid():
            form.save()
            form = User_Profile_Change(instance=current_user)
    
    diction = {'form': form}
    return render(request, 'LogInApp/user_change.html', context=diction)


@login_required
def pass_change(request):
    current_user = request.user
    changed = False
    form = PasswordChangeForm(current_user)
    if request.method=='POST':
        form = PasswordChangeForm(current_user, data=request.POST)
        if form.is_valid():
            form.save()
            changed = True
            
    
    diction = {'form': form, 'changed': changed}
    return render(request, 'LogInApp/change_pass.html', context=diction)


@login_required
def add_profile_pic(request):
    form = Profile_Pic()
    if request.method=='POST':
        form=Profile_Pic(request.POST, request.FILES)
        if form.is_valid():
            user_obj= form.save(commit=False)
            user_obj.user = request.user
            user_obj.save()
            return HttpResponseRedirect(reverse('LogInApp:profile'))
    diction = {'form': form}
    return render(request, 'LogInApp/add_profile_pic.html', context=diction)


@login_required
def change_pro_pic(request):
    form = Profile_Pic(instance=request.user.user_profile)
    
    if request.method == 'POST':
        form = Profile_Pic(request.POST, request.FILES, instance=request.user.user_profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('LogInApp:profile'))
    
    diction = {'form': form}
    return render(request, 'LogInApp/add_profile_pic.html', context=diction)

templates/LogInApp/add_profile_pic.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Profile Picture {% endblock %}


{% block body_block %}
<h2>Add Your Profile Picture:</h2>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit" class="btn btn-success btn-sm">Add</button>
</form>

{% endblock %}

templates/LogInApp/change_pass.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Change Password {% endblock %}

{% block body_block %}

{% if changed %}
<div class="alert alert-success">Password Changed Successfully!</div>
{% endif %}

<h2>Change Your Password!</h2>
<form action="" method="POST">
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit" class="btn btn-warning btn-sm">Change</button>
</form>

{% endblock %}

templates/LogInApp/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Login {% endblock %}

{% block body_block %}
<h2>Log In</h2>

<form action="" method="POST">
    {% csrf_token %}
    {{form|crispy}}
    <button class="btn btn-success btn-sm" type="submit">Login</button>
</form>


{% endblock %}

templates/LogInApp/profile.html
{% extends 'base.html' %}

{% block title_block %} Profile {% endblock %}

{% block body_block %}
<h2>Your Profile</h2>
{% if user.user_profile %}
<img class="img-thumbnail rounded float-left" src="/media/{{user.user_profile.profile_pics}}" alt="image" width="150px">
<br>
<a href="{% url 'LogInApp:change_profile_pic' %}" class="btn btn-info btn-sm">Change Profile Picture</a>
{% else %}
<img class="img-thumbnail rounded float-left" src="/media/profile_pics/avatar.jpg" alt="pics" width="150px"> <br>
<a href="{% url 'LogInApp:add_profile_pic' %}" class="btn btn-info btn-sm">Change Profile Pic</a>
{% endif %}
<br>
<div class="container">
    <p>Username: {{user.username}}</p>
    <p>Name:{{user.first_name}} {{user.last_name}}</p>
    <p>Email:{{user.email}}</p>
</div>
<br>
<p>Update Profile Information: <a href="{% url 'LogInApp:change_profile' %}" class="btn btn-warning btn-sm">Update Profile</a></p>
{% endblock %}

templates/LogInApp/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Create Account||Sign up {% endblock %}

{% block body_block %}

{% if registered %}
<div class="alert alert-success">
    Account Created Successfully! <a href="{% url 'LogInApp:login' %}">Login Here</a>
</div>

{% else %}

<h2>Create a New Account</h2>
<form action="" method="POST">
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit" class="btn btn-success btn-sm">Create</button>
</form>
<br>
<p>Already Have an Account! <a href="{% url 'LogInApp:login' %}">Login Here</a> </p>

{% endif %}


{% endblock %}

templates/LogInApp/user_change.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Change Profile {% endblock %}


{% block body_block %}
<h2>Update Your Data:</h2>
<form action="" method="POST">
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit" class="btn btn-success btn-sm">Change</button>
</form>

{% endblock %}