BlogApp/urls.py
from django.urls import path
from BlogApp import views

app_name = 'BlogApp'

urlpatterns = [
    path('', views.BlogList.as_view(), name='blog_list'),
    path('write/', views.CreateBlog.as_view(), name='create_blog'),
    path('blogdetails/<str:slug>', views.blog_details, name='blog_details'),
    path('liked/<pk>',views.like, name='liked_post'),
    path('unliked/<pk>', views.unlike, name='unliked_post'),
    path('myblogs/', views.MyBlogs.as_view(), name='my_blogs'),
    path('edit_blog/<pk>', views.BlogUpdate.as_view(), name='edit_blog'),
]

BlogProject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('BlogApp.urls')),
    path('account/', include('LogInApp.urls')),
    path('',views.index, name='index'),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LogInApp/urls.py
from django.urls import path
from LogInApp import views


app_name = 'LogInApp'

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('change-profile/', views.user_change, name='change_profile'),
    path('password/', views.pass_change, name='password'),
    path('addprofilepic/', views.add_profile_pic, name='add_profile_pic'),
    path('change_profile/', views.change_pro_pic, name='change_profile_pic'),
]

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.css">
    <title>{% block title_block %} {% endblock %}</title>
  </head>
  <body>
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'index' %}"><img src="/media/blog_images/blogicon.jpg" class="img-fluid" alt="Responsive image" width="40px"></a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'LogInApp:logout' %}">Logout</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'LogInApp:profile' %}"><img src="/media/blog_images/profileicon.jpg" class="img-fluid" alt="Responsive image" width="40px"></a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'LogInApp:signup' %}">SignUp</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'LogInApp:login' %}">Login</a>
            </li>
            {% endif %}
          </ul>

          <div class="nav-item dropdown">
            <a class="btn btn-info dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              @{{user.username}}
            </a>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              {% if user.is_authenticated %}
              <a class="dropdown-item" href="{% url 'BlogApp:create_blog' %}">Write Blog</a>
              <a class="dropdown-item" href="{% url 'BlogApp:my_blogs' %}">My Blogs</a>
              <a class="dropdown-item" href="{% url 'LogInApp:profile' %}">Profile</a>
              <hr>
              <a class="dropdown-item" href="{% url 'LogInApp:logout' %}">Logout</a>
              {% else %}
              <a class="dropdown-item" href="{% url 'LogInApp:login' %}">Login</a>
              <a class="dropdown-item" href="{% url 'LogInApp:signup' %}">Signup</a>
              {% endif %}
              
            </div>
          </div>



      </nav>
      
      <div class="container" style="padding-top: 20px">
        {% block body_block %}

      
        {% endblock %}
      </div>

      


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>